### ISSUE TITLE
getting 500 on calling /model/

### ISSUE THREAD

**Issue by sizhky** [kartik4949/AutoDeploy#2]
![image](https://user-images.githubusercontent.com/3656100/129064129-ef30ebc8-7c4b-4151-bff1-9ec166fb1300.png)

```python
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/yreddy31/anaconda3/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/yreddy31/anaconda3/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/yreddy31/anaconda3/lib/python3.7/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/yreddy31/anaconda3/lib/python3.7/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/yreddy31/anaconda3/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/yreddy31/anaconda3/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/yreddy31/anaconda3/lib/python3.7/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/Users/yreddy31/anaconda3/lib/python3.7/site-packages/prometheus_fastapi_instrumentator/instrumentation.py", line 172, in dispatch_middleware
    raise e from None
  File "/Users/yreddy31/anaconda3/lib/python3.7/site-packages/prometheus_fastapi_instrumentator/instrumentation.py", line 169, in dispatch_middleware
    response = await call_next(request)
  File "/Users/yreddy31/anaconda3/lib/python3.7/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/Users/yreddy31/anaconda3/lib/python3.7/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/Users/yreddy31/anaconda3/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/yreddy31/anaconda3/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/yreddy31/anaconda3/lib/python3.7/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/Users/yreddy31/anaconda3/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/Users/yreddy31/anaconda3/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/Users/yreddy31/anaconda3/lib/python3.7/site-packages/fastapi/routing.py", line 218, in app
    is_coroutine=is_coroutine,
  File "/Users/yreddy31/anaconda3/lib/python3.7/site-packages/fastapi/routing.py", line 126, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 3 validation errors for UserOutputSchema
response -> out
  field required (type=value_error.missing)
response -> probablity
  field required (type=value_error.missing)
response -> status
  field required (type=value_error.missing)
```

am i doing anything wrong?

**Comment by kartik4949** [comment]
@sizhky hey, its been solved it
i passed wrong response_schema for model_details API, 
Thanks
